language: "ko"

rating:
  initial-elo: 1200
  k-factor:
    default: 32
    high-bracket-k: 24
    low-bracket-k: 40
    high-threshold: 1800
    low-threshold: 1000
  draw-score: 0.5

tiers:
  - { name: "&7Bronze",   min-elo: 0,    color: "&7" }
  - { name: "&fSilver",   min-elo: 1100, color: "&f" }
  - { name: "&6Gold",     min-elo: 1300, color: "&6" }
  - { name: "&bPlatinum", min-elo: 1500, color: "&b" }
  - { name: "&3Diamond",  min-elo: 1700, color: "&3" }
  - { name: "&dMaster",   min-elo: 1900, color: "&d" }
  - { name: "&cGrandmaster", min-elo: 2100, color: "&c" }

season:
  enabled: true
  ends-at-epoch-ms: 0
  reset-mode: "FULL"
  soft-carry: 0.25
  snapshot-top-n: 10

queue:
  enable: true
  base-threshold: 150
  expand-per-second: 5
  tick-period-ticks: 40
  max-wait-seconds: 120

match:
  arena-required: false
  pre-countdown-seconds: 3
  teleport-on-match-found: false
  stage-location:
    world: "bskyblock_world"
    x: 0.5
    y: 100.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  on-match-found-commands:
    - "title {p1} title &6매칭!"
    - "title {p1} subtitle &e상대: {p2} &7(Elo {elo2} {tier2})"
    - "title {p2} title &6매칭!"
    - "title {p2} subtitle &e상대: {p1} &7(Elo {elo1} {tier1})"
  on-battle-start-commands:
    - "tellraw {p1} [{\"text\":\"배틀 시작!\",\"color\":\"gold\"}]"
    - "tellraw {p2} [{\"text\":\"배틀 시작!\",\"color\":\"gold\"}]"
  return-to-original: true
  return-delay-seconds: 0
  on-match-ended-commands: []

bans:
  pokemon: ["Mewtwo","Rayquaza"]
  items: ["BEDROCK","BARRIER"]
  items-action: "BLOCK"

auto-result-detection:
  enable-chat-parse: false
  victory-message-patterns:
    - "(?i)\b(?<winner>[A-Za-z0-9_]+)\b .* (?:won|wins) .* \b(?<loser>[A-Za-z0-9_]+)\b"
  draw-message-patterns:
    - "(?i)\b(?<p1>[A-Za-z0-9_]+)\b .* draw .* \b(?<p2>[A-Za-z0-9_]+)\b"

ui:
  prefix: "&7[&a레이팅&7]&r "
  top-header: "&6==== &e레이팅 TOP {page} &6(초기화까지 {left}) ===="
  top-line: "&e#{rank} &f{player} &7- &a{elo} Elo &8{tier}"
  stats-self: "&f당신의 Elo: &a{elo}&f, 티어: {tier} &7| 전적: &a{wins}승 &c{losses}패 &7무승부 {draws}"
  stats-other: "&f{player}의 Elo: &a{elo}&f, 티어: {tier} &7| 전적: &a{wins}승 &c{losses}패 &7무승부 {draws}"
  joined-queue: "&a대기열 참가! 매칭을 기다려주세요."
  already-in-queue: "&e이미 대기열에 있습니다."
  left-queue: "&a대기열에서 나왔습니다."
  not-in-queue: "&e대기열에 없습니다."
  matched: "&6매칭 성사! &f{p1} &7({elo1} {tier1}) &6vs &f{p2} &7({elo2} {tier2})"
  reloaded: "&a구성을 새로고침했습니다."
  admin-only: "&c관리자 전용 명령어입니다."
  set-season: "&a시즌 종료까지 &e{seconds}s &a로 설정됨."
  season-left: "&f시즌 종료까지 남은 시간: &e{left}"
  saved-rewards: "&a보상 {tier} 설정 완료!"
  # 결과 알림
  result-broadcast-enable: true
  result-winner: "&a승리! &f{winner}&7: &a+{deltaW} &8(Elo {oldW}&7→&a{newW})"
  result-loser: "&c패배... &f{loser}&7: &c{deltaL} &8(Elo {oldL}&7→&c{newL})"
  result-draw-p1: "&e무승부 &f{p1}&7: &e{delta1} &8({old1}&7→{new1})"
  result-draw-p2: "&e무승부 &f{p2}&7: &e{delta2} &8({old2}&7→{new2})"
  result-broadcast: "&6[레이팅] &f{winner} &7({oldW}&7→&a{newW}) &6승! &f{loser} &7({oldL}&7→&c{newL})"
