language: "ko"
rating:
  initial-elo: 1200
  k-factor: { default: 32, high-bracket-k: 24, low-bracket-k: 40, high-threshold: 1800, low-threshold: 1000 }
  draw-score: 0.5
tiers:
  - { name: "&7브론즈",   min-elo: 0,    color: "&7" }
  - { name: "&f실버",     min-elo: 1100, color: "&f" }
  - { name: "&6골드",     min-elo: 1300, color: "&6" }
  - { name: "&b플래티넘", min-elo: 1500, color: "&b" }
  - { name: "&3다이아",   min-elo: 1700, color: "&3" }
  - { name: "&d마스터",   min-elo: 1900, color: "&d" }
  - { name: "&c그랜드마스터", min-elo: 2100, color: "&c" }
season: { enabled: true, ends-at-epoch-ms: 0, reset-mode: "FULL", soft-carry: 0.25, snapshot-top-n: 10, timezone: "Asia/Seoul" }
queue: { enable: true, base-threshold: 150, expand-per-second: 5, tick-period-ticks: 40, max-wait-seconds: 120 }
match:
  use-arenas: true
  teleport-on-match-found: true
  pre-countdown-seconds: 3
  stage-location: { world: "world", x: 0.5, y: 100.0, z: 0.5, yaw: 0.0, pitch: 0.0 }
  on-match-found-commands:
    - "tellraw {p1} [{\"text\":\"§6매칭! §e상대: {p2} §7(Elo {elo2} {tier2})\"}]"
    - "tellraw {p2} [{\"text\":\"§6매칭! §e상대: {p1} §7(Elo {elo1} {tier1})\"}]"
  on-battle-start-commands:
    - "tellraw {p1} [{\"text\":\"배틀 시작!\",\"color\":\"gold\"}]"
    - "tellraw {p2} [{\"text\":\"배틀 시작!\",\"color\":\"gold\"}]"
  # 네 서버는 이 명령으로 배틀이 걸립니다.
  battle-start-command: "pokebattle {p1} {p2}"
auto-result-detection:
  # 자동 결과 감지 켜기
  enable-chat-parse: true

  # (있으면 강력추천) ProtocolLib로 플레이어별 결과 메시지까지 확실히 포착
  protocol-chat-hook: true

  # 네 서버에 실제로 뜨는 한국어 결과 문구
  korean:
    victory: "배틀에서 이겼다!"
    defeat:  "모든포켓몬이 쓰러졌다!"

  # (방송형 공지용 백업 패턴 — 필요시 유지)
  victory-message-patterns:
    - '(?i)\b(?<winner>[A-Za-z0-9_가-힣]+)\b .* (?:won|wins|승리) .* \b(?<loser>[A-Za-z0-9_가-힣]+)\b'
  draw-message-patterns:
    - '(?i)\b(?<p1>[A-Za-z0-9_가-힣]+)\b .* (?:draw|무승부) .* \b(?<p2>[A-Za-z0-9_가-힣]+)\b'

bans:
  pokemon: ["Mewtwo","Rayquaza"]
  items: ["BEDROCK","BARRIER"]
  items-action: "BLOCK"
auto-result-detection:
  enable-chat-parse: false
  victory-message-patterns: ["(?i)\b(?<winner>[A-Za-z0-9_가-힣]+)\b .* (?:won|wins|승리) .* \b(?<loser>[A-Za-z0-9_가-힣]+)\b"]
  draw-message-patterns: ["(?i)\b(?<p1>[A-Za-z0-9_가-힣]+)\b .* (?:draw|무승부) .* \b(?<p2>[A-Za-z0-9_가-힣]+)\b"]
ui: { prefix: "&7[&a레이팅&7]&r " }
storage:
  ratings-file: "ratings.yml"
debug:
  matchmaking: true
  battle: true
