language: ko

rating:
  default: 1200
  k-factor:
    default: 32
    high-threshold: 1800
    low-threshold: 1000
    high-bracket-k: 24
    low-bracket-k: 40
  provisional-games: 0
  provisional-multiplier: 1.0

queue:
  enable: true
  base-threshold: 300
  expand-per-second: 10
  tick-period-ticks: 20
  max-wait-seconds: 180

match:
  arena-required: true
  stage-location:
    world: bskyblock_world
    x: 100.5
    y: 65.0
    z: 100.5
    yaw: 0
    pitch: 0

detection:
  use-packet-hook: true
  finalize-wait-ms: 1700

  win-message-patterns:
    - '(?i)배틀에서\s*이겼다!?$'
    - '(?i)전투에서\s*이겼다!?$'
  lose-message-patterns:
    - '(?i)배틀에서\s*졌[다!]*$'
    - '(?i)패배했[다!]*$'
  draw-message-patterns:
    - '(?i)무\s*승\s*부'
    - '(?i)비겼다!?$'
  forfeit-message-patterns:
    - '(?i)도주했[다!]*$'
    - '(?i)항복했[다!]*$'
    - '(?i)배틀에서\s*포기했[다!]*$'
    - '(?i)전투에서\s*포기했[다!]*$'
  faint-all-hint-patterns:
    - '(?i)모든\s*포켓몬(이|이[가])\s*쓰러졌다!?$'

ui:
  admin-only: '&c관리자 전용 명령입니다.'
  arena-created: '&a아레나 &e{arena}&a가 생성되었습니다.'
  arena-updated: '&a아레나 &e{arena}&a가 업데이트되었습니다.'
  arena-enabled: '&a아레나 &e{arena}&a 활성화: &e{enabled}'
  no-arena: '&c사용 가능한 아레나가 없습니다.'
  queued: '&a매칭 대기열에 등록되었습니다.'
  left-queue: '&e대기열에서 나갔습니다.'
  already-in-queue: '&e이미 대기열에 있습니다.'
  not-in-queue: '&e대기열에 없습니다.'
  match-start: '&6{p1}&7 vs &6{p2}&7 매치 시작!'
  stats:
    header: '&e{player}&7의 레이팅: &b{rating}&7, 전적 &a{win}&7승 &c{loss}&7패 &7/ 무승부 {draw} 도주 {forfeit}'
    line: '&7최근 결과: {recent}'


tier:
  bands:
    - {name: D, min: 0}
    - {name: C, min: 1100}
    - {name: B, min: 1300}
    - {name: A, min: 1500}
    - {name: S, min: 1700}

bans:
  command-blacklist:
    - spawn
    - home
    - tp
    - tpa

ui:
  queue-actionbar:
    enable: true
    period-ticks: 40

battle:
  timeout-seconds: 0  # 0=off, >0이면 시간초과 시 무승부로 처리

rewards:
  season:
    commands:
      - "give {player} diamond 3"
