language: ko

rating:
  default: 1200
  k-factor:
    default: 32
    high-threshold: 1800
    low-threshold: 1000
    high-bracket-k: 24
    low-bracket-k: 40
  provisional-games: 0
  provisional-multiplier: 1.0

queue:
  enable: true
  base-threshold: 300
  expand-per-second: 10
  tick-period-ticks: 20
  max-wait-seconds: 180

match:
  arena-required: true
  stage-location:
    world: bskyblock_world
    x: 100.5
    y: 65.0
    z: 100.5
    yaw: 0
    pitch: 0

detection:
  use-packet-hook: true
  finalize-wait-ms: 1700

  win-message-patterns:
    - '(?i)배틀에서\s*이겼다!?$'
    - '(?i)전투에서\s*이겼다!?$'

  lose-message-patterns:
    - '(?i)배틀에서\s*졌[다!]*$'
    - '(?i)패배했[다!]*$'

  draw-message-patterns:
    - '(?i)무\s*승\s*부'
    - '(?i)비겼다!?$'

  forfeit-message-patterns:
    - '(?i)도주했[다!]*$'
    - '(?i)항복했[다!]*$'
    - '(?i)배틀에서\s*포기했[다!]*$'
    - '(?i)전투에서\s*포기했[다!]*$'

  faint-all-hint-patterns:
    - '(?i)모든\s*포켓몬(이|이[가])\s*쓰러졌다!?$'

ui:
  admin-only: '&c관리자 전용 명령입니다.'
  arena-created: '&a아레나 &e{arena}&a가 생성되었습니다.'
  arena-updated: '&a아레나 &e{arena}&a가 업데이트되었습니다.'
  arena-enabled: '&a아레나 &e{arena}&a 활성화: &e{enabled}'
  no-arena: '&c사용 가능한 아레나가 없습니다.'
  queued: '&a매칭 대기열에 등록되었습니다.'
  left-queue: '&e대기열에서 나갔습니다.'
  already-in-queue: '&e이미 대기열에 있습니다.'
  not-in-queue: '&e대기열에 없습니다.'
  match-start: '&6{p1}&7 vs &6{p2}&7 매치 시작!'
  stats:
    header: '&e{player}&7의 레이팅: &b{rating}&7, 전적 &a{win}&7승 &c{loss}&7패 &7/ 무승부 {draw} 도주 {forfeit}'
    line: '&7최근 결과: {recent}'
  queue-actionbar:
    enable: true
    period-ticks: 40
  help:
    header: '&6&l[ 픽셀몬 레이팅 도움말 ]'
    lines:
      - '&e/레이팅 참가 &7- 대기열에 참여합니다.'
      - '&e/레이팅 취소 &7- 대기열에서 나갑니다.'
      - '&e/레이팅 전적 [닉] &7- 본인/지정 유저 전적을 확인합니다.'
      - '&e/레이팅 랭킹 [페이지] &7- Elo 상위 랭킹을 확인합니다.'
      - '&e/레이팅 보상 &7- 시즌 보상 GUI(티어 기준).'
      - '&e/레이팅 아레나 생성 <이름> &7- 아레나 생성 (관리자)'
      - '&e/레이팅 아레나 스폰 <이름> <a|b> &7- 아레나 스폰 지정 (관리자)'
      - '&e/레이팅 아레나 활성화 <이름> <true|false> &7- 아레나 ON/OFF (관리자)'
      - '&e/레이팅 아레나 목록 &7- 아레나 상태 보기 (관리자)'
      - '&e/레이팅 시즌종료 <월> <일> <시> <분> [초] &7- 시즌 종료 시각 설정 (관리자)'
    footer: '&7티어/보상/설정: plugins/UltimatePixelmonRating/config.yml'
  ranking:
    header: '&6&l[ 레이팅 랭킹 ] &7(페이지 {page})'
    line: '&e#{rank} &f{name} &7- &b{rating} &7점 &8(&a{win}&7승/&c{loss}&7패/&7{draw}무/{forfeit}도주)'
    footer: '&7시즌 종료: {season} &8| &7설정: &e/레이팅 시즌종료 <월> <일> <시> <분>'

tier:
  bands:
    - {name: D, min: 0}
    - {name: C, min: 1100}
    - {name: B, min: 1300}
    - {name: A, min: 1500}
    - {name: S, min: 1700}

bans:
  command-blacklist:
    - spawn
    - home
    - tp
    - tpa

battle:
  timeout-seconds: 0  # 0=off, >0이면 시간초과 시 무승부로 처리

rewards:
  season:
    commands:
      - "give {player} diamond 3"
