name: UltimatePixelmonRating
main: com.minkang.ultimate.pixelrating.UltimatePixelmonRatingPlugin
version: 1.9.2
api-version: 1.16
author: minkang
commands:
  레이팅:
    description: Pixelmon Elo / Rating commands
    usage: /레이팅
    aliases: [rating, elo]
