name: UltimatePixelmonRating
main: com.minkang.ultimate.pixelrating.UltimatePixelmonRatingPlugin
version: 1.6.1
api-version: 1.16
author: Minkang
commands:
  레이팅:
    description: 픽셀몬 레이팅 시스템
    usage: /레이팅 도움말
permissions:
  upr.admin:
    default: op
    description: 레이팅 관리자 권한