name: UltimatePixelmonRating
main: com.minkang.ultimate.pixelrating.UltimatePixelmonRatingPlugin
version: 1.4.5
api-version: 1.16
author: Minkang
description: Pixelmon Elo + 티어 + 시즌 + 보상GUI + 아레나 + 결과/복귀
commands:
  레이팅:
    description: 픽셀몬 레이팅 시스템
    usage: /레이팅 도움말
permissions:
  upr.admin:
    default: op
    description: 레이팅 관리자 권한

  upr.battle.bypass:
    default: op
    description: 배틀 중 명령어 차단 우회
