package com.minkang.ultimate.pixelrating;
import org.bukkit.Bukkit; import org.bukkit.ChatColor; import org.bukkit.Material; import org.bukkit.entity.*; import org.bukkit.event.*; import org.bukkit.event.inventory.*; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta;
public class RewardGUI implements Listener {
  private final UltimatePixelmonRatingPlugin plugin; private final RewardStore store; private final java.util.Map<java.util.UUID,String> editingTier=new java.util.HashMap<>();
  public RewardGUI(UltimatePixelmonRatingPlugin plugin, RewardStore store){ this.plugin=plugin; this.store=store; }
  public void open(Player p){ Inventory inv=Bukkit.createInventory(p,27,color("&8티어 보상 설정")); java.util.List<?> list=plugin.getConfig().getList("tiers"); for(int i=0;i<Math.min(7,list.size());i++){ String name; Object o=list.get(i); if(o instanceof java.util.Map) name=String.valueOf(((java.util.Map<?,?>)o).get("name")); else name="Tier "+(i+1); ItemStack it=new ItemStack(Material.PAPER); ItemMeta m=it.getItemMeta(); m.setDisplayName(color("&e"+name)); java.util.List<String> lore=new java.util.ArrayList<>(); lore.add(color("&7좌클릭: 샘플 명령 추가")); lore.add(color("&7우클릭: 보상 비우기")); m.setLore(lore); it.setItemMeta(m); inv.setItem(10+i, it);} p.openInventory(inv); }
  @EventHandler public void onClick(InventoryClickEvent e){ if(e.getView().getTitle()==null || !ChatColor.stripColor(e.getView().getTitle()).equals("티어 보상 설정")) return; e.setCancelled(true); ItemStack it=e.getCurrentItem(); if(it==null || it.getType()==Material.AIR) return; String tier=ChatColor.stripColor(it.getItemMeta().getDisplayName()).replace("§e",""); Player p=(Player)e.getWhoClicked(); java.util.List<String> cmds=store.getCommandsForTier(tier); if(e.isLeftClick()){ cmds.add("give {player} DIAMOND 1"); store.setCommandsForTier(tier, cmds); p.sendMessage(color(plugin.getConfig().getString("ui.prefix","")+"&a샘플 보상 명령이 추가되었습니다.")); } else if(e.isRightClick()){ store.setCommandsForTier(tier, new java.util.ArrayList<>()); p.sendMessage(color(plugin.getConfig().getString("ui.prefix","")+"&c해당 티어 보상을 비웠습니다.")); } editingTier.put(p.getUniqueId(), tier); }
  @EventHandler public void onClose(InventoryCloseEvent e){ if(e.getView().getTitle()==null || !ChatColor.stripColor(e.getView().getTitle()).equals("티어 보상 설정")) return; HumanEntity he=e.getPlayer(); String tier=editingTier.remove(he.getUniqueId()); if(tier!=null){ he.sendMessage(color(plugin.getConfig().getString("ui.prefix","") + "&e'"+tier+"' 보상 설정이 저장되었습니다.")); } }
  private String color(String s){ return ChatColor.translateAlternateColorCodes('&', s); }
}