package com.minkang.ultimate.pixelrating;
import org.bukkit.Bukkit; import org.bukkit.ChatColor; import org.bukkit.scheduler.BukkitRunnable; import java.util.Locale; import java.util.TimeZone;
public class SeasonManager { private final UltimatePixelmonRatingPlugin plugin; private int taskId=-1;
  public SeasonManager(UltimatePixelmonRatingPlugin plugin){ this.plugin=plugin; }
  public long endsAtMs(){ return plugin.getConfig().getLong("season.ends-at-epoch-ms",0L); }
  public String remainingString(){ long ms=endsAtMs()-System.currentTimeMillis(); if(ms<=0) return "종료됨"; long s=ms/1000; long d=s/86400; s%=86400; long h=s/3600; s%=3600; long m=s/60; s%=60; return String.format(Locale.KOREA,"%d일 %02d:%02d:%02d",d,h,m,s); }
  public void setSeasonByComponents(int mo,int d,int h,int mi){ java.util.Calendar cal=java.util.Calendar.getInstance(java.util.TimeZone.getTimeZone(plugin.getConfig().getString("season.timezone","Asia/Seoul"))); cal.set(java.util.Calendar.MONTH,mo-1); cal.set(java.util.Calendar.DAY_OF_MONTH,d); cal.set(java.util.Calendar.HOUR_OF_DAY,h); cal.set(java.util.Calendar.MINUTE,mi); cal.set(java.util.Calendar.SECOND,0); cal.set(java.util.Calendar.MILLISECOND,0); plugin.getConfig().set("season.ends-at-epoch-ms",cal.getTimeInMillis()); plugin.saveConfig(); }
  public void setSeasonByString(String dt){ try{ String tz=plugin.getConfig().getString("season.timezone","Asia/Seoul"); java.text.SimpleDateFormat fmt=new java.text.SimpleDateFormat("yyyy-MM-dd_HH:mm:ss"); fmt.setTimeZone(TimeZone.getTimeZone(tz)); long ms=fmt.parse(dt).getTime(); plugin.getConfig().set("season.ends-at-epoch-ms",ms); plugin.saveConfig(); }catch(Exception e){ throw new IllegalArgumentException("형식: yyyy-MM-dd_HH:mm:ss"); } }
  public void startTicker(){ stopTicker(); taskId=new BukkitRunnable(){ @Override public void run(){ if(!plugin.getConfig().getBoolean("season.enabled",true)) return; long now=System.currentTimeMillis(); long end=endsAtMs(); if(end>0 && now>=end){ Bukkit.broadcastMessage(color(plugin.getConfig().getString("ui.prefix","")+"&c시즌이 종료되었습니다!")); plugin.getConfig().set("season.ends-at-epoch-ms",0L); plugin.saveConfig(); } } }.runTaskTimer(plugin,20L,20L).getTaskId(); }
  public void stopTicker(){ if(taskId!=-1){ Bukkit.getScheduler().cancelTask(taskId); taskId=-1; } } private String color(String s){ return ChatColor.translateAlternateColorCodes('&', s); }
}