name: Build (Java 8 / 1.16.5)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Install local ProtocolLib into Maven repo
        run: |
          if [ -f lib/ProtocolLib.jar ]; then
            mvn -q install:install-file               -Dfile=lib/ProtocolLib.jar               -DgroupId=com.comphenix.protocol               -DartifactId=ProtocolLib               -Dversion=local               -Dpackaging=jar
          fi

      - name: Build with Maven
        run: mvn -q -DskipTests clean package

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: UltimatePixelmonRating-${{ github.run_number }}
          path: |
            target/*.jar
            !target/*-sources.jar
            !target/*-javadoc.jar
          if-no-files-found: error
