name: Build UltimatePixelmonRating

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Build with Maven (quiet, skip tests)
        run: mvn -q -DskipTests package

      - name: Package plugin & resources
        run: |
          chmod +x ./build_and_package.sh || true
          ./build_and_package.sh
        shell: bash

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: UltimatePixelmonRating-jar
          path: |
            target/UltimatePixelmonRating-*.jar

      - name: Upload built bundle (out/)
        uses: actions/upload-artifact@v4
        with:
          name: UltimatePixelmonRating-out
          path: |
            out/**
